/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-03-15 12:08:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clogin_005fsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Dashboard | Mommy's Kitchen</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Poppins:wght@300;400;500;600&display=swap\" rel=\"stylesheet\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"/>\n");
      out.write("  <style>\n");
      out.write("    *, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }\n");
      out.write("    :root { --bg:#0d0d0d; --surface:#1a1a1a; --border:rgba(255,255,255,0.08); --accent:#e8943a; --text:#f0f0f0; --muted:#777; }\n");
      out.write("    body { font-family:'Poppins',sans-serif; background:var(--bg); color:var(--text); min-height:100vh; position:relative; overflow-x:hidden; }\n");
      out.write("    body::before, body::after { content:''; position:fixed; border-radius:50%; filter:blur(100px); opacity:0.12; pointer-events:none; z-index:0; }\n");
      out.write("    body::before { width:600px; height:600px; background:var(--accent); top:-200px; left:-200px; }\n");
      out.write("    body::after  { width:500px; height:500px; background:#c0392b; bottom:-150px; right:-150px; }\n");
      out.write("    nav { position:fixed; top:0; width:100%; z-index:100; display:flex; justify-content:space-between; align-items:center; padding:16px 6%; background:rgba(13,13,13,0.88); backdrop-filter:blur(14px); border-bottom:1px solid var(--border); }\n");
      out.write("    .logo { font-family:'Playfair Display',serif; font-size:1.4rem; font-weight:700; color:var(--accent); text-decoration:none; }\n");
      out.write("    .logo span { color:var(--text); }\n");
      out.write("    .nav-right { display:flex; align-items:center; gap:16px; }\n");
      out.write("    .nav-badge { background:rgba(232,148,58,0.12); color:var(--accent); border:1px solid rgba(232,148,58,0.25); border-radius:20px; padding:4px 12px; font-size:0.72rem; font-weight:600; }\n");
      out.write("    .nav-logout { color:var(--muted); text-decoration:none; font-size:0.82rem; display:flex; align-items:center; gap:6px; transition:color 0.2s; }\n");
      out.write("    .nav-logout:hover { color:var(--accent); }\n");
      out.write("    .main { padding:100px 6% 60px; position:relative; z-index:1; }\n");
      out.write("    .welcome-banner { background:linear-gradient(135deg,rgba(232,148,58,0.12),rgba(192,57,43,0.06)); border:1px solid rgba(232,148,58,0.2); border-radius:20px; padding:32px 36px; display:flex; align-items:center; gap:24px; margin-bottom:36px; position:relative; overflow:hidden; }\n");
      out.write("    .welcome-banner::before { content:'🍛'; position:absolute; right:24px; top:50%; transform:translateY(-50%); font-size:4rem; opacity:0.15; }\n");
      out.write("    .welcome-avatar { width:60px; height:60px; border-radius:16px; background:linear-gradient(135deg,var(--accent),#c0392b); display:flex; align-items:center; justify-content:center; font-size:1.5rem; flex-shrink:0; box-shadow:0 8px 20px rgba(232,148,58,0.3); }\n");
      out.write("    .welcome-text h2 { font-family:'Playfair Display',serif; font-size:1.5rem; }\n");
      out.write("    .welcome-text h2 span { color:var(--accent); }\n");
      out.write("    .welcome-text p { color:var(--muted); font-size:0.85rem; margin-top:4px; }\n");
      out.write("    .section-title { font-size:0.72rem; font-weight:600; letter-spacing:1px; text-transform:uppercase; color:var(--muted); margin-bottom:16px; display:flex; align-items:center; gap:8px; }\n");
      out.write("    .section-title::after { content:''; flex:1; height:1px; background:var(--border); }\n");
      out.write("    .action-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); gap:16px; }\n");
      out.write("    .action-card { background:var(--surface); border:1px solid var(--border); border-radius:16px; padding:24px; text-decoration:none; color:var(--text); display:flex; flex-direction:column; gap:14px; transition:transform 0.25s,box-shadow 0.25s,border-color 0.25s; }\n");
      out.write("    .action-card:hover { transform:translateY(-4px); box-shadow:0 16px 40px rgba(0,0,0,0.4); border-color:rgba(232,148,58,0.3); }\n");
      out.write("    .action-card-icon { width:44px; height:44px; border-radius:12px; display:flex; align-items:center; justify-content:center; font-size:1.1rem; }\n");
      out.write("    .icon-orange{background:rgba(232,148,58,0.12);} .icon-red{background:rgba(192,57,43,0.12);} .icon-green{background:rgba(46,213,115,0.1);} .icon-blue{background:rgba(52,152,219,0.1);}\n");
      out.write("    .c-orange{color:#e8943a;} .c-red{color:#e74c3c;} .c-green{color:#2ed573;} .c-blue{color:#3498db;}\n");
      out.write("    .action-card h4 { font-size:0.95rem; font-weight:600; }\n");
      out.write("    .action-card p  { font-size:0.78rem; color:var(--muted); line-height:1.5; }\n");
      out.write("    .action-card .arrow { font-size:0.75rem; color:var(--muted); display:flex; align-items:center; gap:4px; margin-top:auto; transition:color 0.2s; }\n");
      out.write("    .action-card:hover .arrow { color:var(--accent); }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");

// Get name from request attribute first, then fallback to cookie
String cfName = (String) request.getAttribute("cfname");
if (cfName == null) {
    Cookie[] cookies = request.getCookies();
    if (cookies != null) {
        for (Cookie c : cookies) {
            if (c.getName().equals("cname")) {
                cfName = c.getValue();
                break;
            }
        }
    }
}
if (cfName == null) cfName = "Guest";

      out.write("\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"welcome.html\" class=\"logo\">Mommy's<span> Kitchen</span></a>\n");
      out.write("    <div class=\"nav-right\">\n");
      out.write("      <span class=\"nav-badge\"><i class=\"fa fa-user\"></i> &nbsp;CUSTOMER</span>\n");
      out.write("      <a href=\"welcome.html\" class=\"nav-logout\"><i class=\"fa fa-right-from-bracket\"></i> Logout</a>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("  <div class=\"main\">\n");
      out.write("    <div class=\"welcome-banner\">\n");
      out.write("      <div class=\"welcome-avatar\">🍛</div>\n");
      out.write("      <div class=\"welcome-text\">\n");
      out.write("        <h2>Welcome, <span>");
      out.print( cfName );
      out.write("!</span></h2>\n");
      out.write("        <p>What would you like to do today?</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"section-title\"><i class=\"fa fa-bolt\"></i> Quick Actions</div>\n");
      out.write("    <div class=\"action-grid\">\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "CLink.html", out, false);
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
