/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-03-15 12:06:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import test.CRegBean;

public final class CustomerProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("test.CRegBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

CRegBean crb = (CRegBean) application.getAttribute("CbeanRef");
String cuname = null;
if (crb == null) {
    // Try cookie
    Cookie[] cookies = request.getCookies();
    if (cookies != null)
        for (Cookie c : cookies)
            if (c.getName().equals("cname")) cuname = c.getValue();
    if (cuname == null) { response.sendRedirect("Clogin.html"); return; }
}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>My Profile | Mommy's Kitchen</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Poppins:wght@300;400;500;600&display=swap\" rel=\"stylesheet\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"/>\n");
      out.write("  <style>\n");
      out.write("    *, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }\n");
      out.write("    :root { --bg:#0d0d0d; --surface:#1a1a1a; --surface2:#222; --border:rgba(255,255,255,0.08); --accent:#e8943a; --text:#f0f0f0; --muted:#777; }\n");
      out.write("    body { font-family:'Poppins',sans-serif; background:var(--bg); color:var(--text); min-height:100vh; display:flex; align-items:center; justify-content:center; padding:30px 20px; position:relative; overflow:hidden; }\n");
      out.write("    body::before, body::after { content:''; position:fixed; border-radius:50%; filter:blur(90px); opacity:0.13; pointer-events:none; z-index:0; }\n");
      out.write("    body::before { width:500px; height:500px; background:var(--accent); top:-160px; left:-160px; }\n");
      out.write("    body::after  { width:400px; height:400px; background:#c0392b; bottom:-120px; right:-120px; }\n");
      out.write("    .back-link { position:fixed; top:24px; left:28px; z-index:10; color:var(--muted); text-decoration:none; font-size:0.85rem; display:flex; align-items:center; gap:6px; transition:color 0.2s; }\n");
      out.write("    .back-link:hover { color:var(--accent); }\n");
      out.write("    .card { background:var(--surface); border:1px solid var(--border); border-radius:24px; padding:44px 40px; width:100%; max-width:500px; position:relative; z-index:1; box-shadow:0 30px 80px rgba(0,0,0,0.5); }\n");
      out.write("    .profile-header { text-align:center; margin-bottom:32px; }\n");
      out.write("    .avatar { width:80px; height:80px; background:linear-gradient(135deg,var(--accent),#c0392b); border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:2rem; margin:0 auto 14px; box-shadow:0 8px 24px rgba(232,148,58,0.3); }\n");
      out.write("    .profile-header h2 { font-family:'Playfair Display',serif; font-size:1.5rem; }\n");
      out.write("    .profile-header h2 span { color:var(--accent); }\n");
      out.write("    .profile-header p { color:var(--muted); font-size:0.82rem; margin-top:5px; }\n");
      out.write("    .role-badge { display:inline-flex; align-items:center; gap:6px; background:rgba(232,148,58,0.12); color:var(--accent); border:1px solid rgba(232,148,58,0.25); border-radius:20px; padding:4px 14px; font-size:0.72rem; font-weight:600; margin-bottom:10px; }\n");
      out.write("    .section-label { font-size:0.68rem; font-weight:600; letter-spacing:1px; text-transform:uppercase; color:var(--muted); margin:20px 0 12px; display:flex; align-items:center; gap:8px; }\n");
      out.write("    .section-label::after { content:''; flex:1; height:1px; background:var(--border); }\n");
      out.write("    .section-label i { color:var(--accent); }\n");
      out.write("    .detail-grid { background:var(--surface2); border:1px solid var(--border); border-radius:14px; overflow:hidden; }\n");
      out.write("    .detail-row { display:flex; align-items:center; padding:12px 16px; gap:12px; border-bottom:1px solid var(--border); }\n");
      out.write("    .detail-row:last-child { border-bottom:none; }\n");
      out.write("    .detail-icon { width:32px; height:32px; border-radius:8px; background:rgba(232,148,58,0.1); display:flex; align-items:center; justify-content:center; flex-shrink:0; }\n");
      out.write("    .detail-icon i { color:var(--accent); font-size:0.78rem; }\n");
      out.write("    .detail-label { font-size:0.68rem; color:var(--muted); text-transform:uppercase; letter-spacing:0.5px; margin-bottom:2px; }\n");
      out.write("    .detail-value { font-size:0.9rem; font-weight:500; }\n");
      out.write("    .btn-back { display:flex; align-items:center; justify-content:center; gap:8px; width:100%; padding:14px; background:linear-gradient(135deg,var(--accent),#d4782a); color:#0d0d0d; font-family:'Poppins',sans-serif; font-size:0.92rem; font-weight:700; border:none; border-radius:12px; cursor:pointer; margin-top:28px; text-decoration:none; transition:all 0.25s; box-shadow:0 4px 20px rgba(232,148,58,0.3); }\n");
      out.write("    .btn-back:hover { transform:translateY(-2px); }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <a href=\"clogin_success.jsp\" class=\"back-link\"><i class=\"fa fa-arrow-left\"></i> Dashboard</a>\n");
      out.write("  <div class=\"card\">\n");
      out.write("    <div class=\"profile-header\">\n");
      out.write("      <div class=\"avatar\">🍛</div>\n");
      out.write("      <div class=\"role-badge\"><i class=\"fa fa-user\"></i> &nbsp;CUSTOMER</div>\n");
      out.write("      <h2>My <span>Profile</span></h2>\n");
      out.write("      <p>Your account details</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (crb != null) { 
      out.write("\n");
      out.write("    <div class=\"section-label\"><i class=\"fa fa-user\"></i> Personal Info</div>\n");
      out.write("    <div class=\"detail-grid\">\n");
      out.write("      <div class=\"detail-row\"><div class=\"detail-icon\"><i class=\"fa fa-user\"></i></div><div><div class=\"detail-label\">Username</div><div class=\"detail-value\">");
      out.print( crb.getCuName() );
      out.write("</div></div></div>\n");
      out.write("      <div class=\"detail-row\"><div class=\"detail-icon\"><i class=\"fa fa-id-card\"></i></div><div><div class=\"detail-label\">Full Name</div><div class=\"detail-value\">");
      out.print( crb.getCfName() );
      out.write(' ');
      out.print( crb.getClName() );
      out.write("</div></div></div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"section-label\"><i class=\"fa fa-address-book\"></i> Contact</div>\n");
      out.write("    <div class=\"detail-grid\">\n");
      out.write("      <div class=\"detail-row\"><div class=\"detail-icon\"><i class=\"fa fa-envelope\"></i></div><div><div class=\"detail-label\">Email</div><div class=\"detail-value\">");
      out.print( crb.getCmid() );
      out.write("</div></div></div>\n");
      out.write("      <div class=\"detail-row\"><div class=\"detail-icon\"><i class=\"fa fa-phone\"></i></div><div><div class=\"detail-label\">Phone</div><div class=\"detail-value\">");
      out.print( crb.getCmob() );
      out.write("</div></div></div>\n");
      out.write("      <div class=\"detail-row\"><div class=\"detail-icon\"><i class=\"fa fa-map-pin\"></i></div><div><div class=\"detail-label\">Location</div><div class=\"detail-value\">");
      out.print( crb.getCloc() );
      out.write("</div></div></div>\n");
      out.write("      <div class=\"detail-row\"><div class=\"detail-icon\"><i class=\"fa fa-location-dot\"></i></div><div><div class=\"detail-label\">Address</div><div class=\"detail-value\">");
      out.print( crb.getCaddr() );
      out.write("</div></div></div>\n");
      out.write("    </div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <p style=\"text-align:center;color:var(--muted);margin:20px 0;\">Please login again to view profile.</p>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <a href=\"clogin_success.jsp\" class=\"btn-back\"><i class=\"fa fa-arrow-left\"></i> Back to Dashboard</a>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
