/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-03-15 11:25:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005ferror_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Login Failed | Mommy's Kitchen</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Poppins:wght@300;400;500;600&display=swap\" rel=\"stylesheet\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"/>\n");
      out.write("  <style>\n");
      out.write("    *, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }\n");
      out.write("    :root { --bg:#0d0d0d; --surface:#1a1a1a; --border:rgba(255,255,255,0.08); --accent:#e8943a; --red:#c0392b; --text:#f0f0f0; --muted:#777; }\n");
      out.write("    body { font-family:'Poppins',sans-serif; background:var(--bg); color:var(--text); min-height:100vh; display:flex; align-items:center; justify-content:center; padding:20px; position:relative; overflow:hidden; }\n");
      out.write("    body::before, body::after { content:''; position:fixed; border-radius:50%; filter:blur(90px); opacity:0.15; pointer-events:none; z-index:0; }\n");
      out.write("    body::before { width:500px; height:500px; background:var(--red); top:-160px; right:-160px; }\n");
      out.write("    body::after  { width:400px; height:400px; background:var(--accent); bottom:-120px; left:-120px; }\n");
      out.write("    .card { background:var(--surface); border:1px solid var(--border); border-radius:24px; padding:48px 40px; width:100%; max-width:420px; position:relative; z-index:1; box-shadow:0 30px 80px rgba(0,0,0,0.5); text-align:center; }\n");
      out.write("    .error-icon { width:72px; height:72px; background:rgba(192,57,43,0.12); border:1px solid rgba(192,57,43,0.25); border-radius:50%; display:flex; align-items:center; justify-content:center; margin:0 auto 20px; font-size:1.8rem; }\n");
      out.write("    h2 { font-family:'Playfair Display',serif; font-size:1.6rem; margin-bottom:10px; }\n");
      out.write("    h2 span { color:#e74c3c; }\n");
      out.write("    .error-msg { background:rgba(192,57,43,0.08); border:1px solid rgba(192,57,43,0.2); border-radius:12px; padding:14px 18px; color:#e74c3c; font-size:0.88rem; margin:20px 0 28px; display:flex; align-items:center; gap:10px; text-align:left; }\n");
      out.write("    .btn-back { display:inline-flex; align-items:center; gap:8px; padding:13px 32px; border-radius:50px; background:linear-gradient(135deg,var(--accent),#d4782a); color:#0d0d0d; font-family:'Poppins',sans-serif; font-size:0.9rem; font-weight:600; text-decoration:none; transition:all 0.25s; box-shadow:0 4px 20px rgba(232,148,58,0.3); }\n");
      out.write("    .btn-back:hover { transform:translateY(-2px); box-shadow:0 8px 28px rgba(232,148,58,0.45); }\n");
      out.write("    .links { margin-top:20px; font-size:0.82rem; color:var(--muted); }\n");
      out.write("    .links a { color:var(--accent); text-decoration:none; font-weight:500; }\n");
      out.write("    .links a:hover { text-decoration:underline; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
 String msg = (String) request.getAttribute("msg"); 
      out.write("\n");
      out.write("  <div class=\"card\">\n");
      out.write("    <div class=\"error-icon\">❌</div>\n");
      out.write("    <h2>Login <span>Failed</span></h2>\n");
      out.write("    <p style=\"color:var(--muted);font-size:0.85rem;\">We couldn't verify your credentials</p>\n");
      out.write("    <div class=\"error-msg\">\n");
      out.write("      <i class=\"fa fa-circle-exclamation\"></i>\n");
      out.write("      ");
      out.print( msg != null ? msg : "Invalid username or password. Please try again." );
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <a href=\"javascript:history.back()\" class=\"btn-back\">\n");
      out.write("      <i class=\"fa fa-arrow-left\"></i> Try Again\n");
      out.write("    </a>\n");
      out.write("    <div class=\"links\">\n");
      out.write("      <p style=\"margin-top:14px;\">Go back to <a href=\"welcome.html\">Home</a></p>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
