/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-03-15 11:25:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import test.RegBean;

public final class View_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("test.RegBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Review Registration | Mommy's Kitchen</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Poppins:wght@300;400;500;600&display=swap\" rel=\"stylesheet\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"/>\n");
      out.write("  <style>\n");
      out.write("    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("    :root {\n");
      out.write("      --bg:      #0d0d0d;\n");
      out.write("      --surface: #1a1a1a;\n");
      out.write("      --surface2:#222;\n");
      out.write("      --border:  rgba(255,255,255,0.08);\n");
      out.write("      --accent:  #e8943a;\n");
      out.write("      --red:     #c0392b;\n");
      out.write("      --text:    #f0f0f0;\n");
      out.write("      --muted:   #777;\n");
      out.write("    }\n");
      out.write("    body {\n");
      out.write("      font-family: 'Poppins', sans-serif;\n");
      out.write("      background: var(--bg); color: var(--text);\n");
      out.write("      min-height: 100vh;\n");
      out.write("      display: flex; align-items: center; justify-content: center;\n");
      out.write("      padding: 30px 20px; position: relative; overflow: hidden;\n");
      out.write("    }\n");
      out.write("    body::before, body::after {\n");
      out.write("      content: ''; position: fixed; border-radius: 50%;\n");
      out.write("      filter: blur(90px); opacity: 0.13; pointer-events: none; z-index: 0;\n");
      out.write("    }\n");
      out.write("    body::before {\n");
      out.write("      width: 500px; height: 500px; background: var(--red);\n");
      out.write("      top: -160px; right: -160px;\n");
      out.write("    }\n");
      out.write("    body::after {\n");
      out.write("      width: 400px; height: 400px; background: var(--accent);\n");
      out.write("      bottom: -120px; left: -120px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card {\n");
      out.write("      background: var(--surface);\n");
      out.write("      border: 1px solid var(--border);\n");
      out.write("      border-radius: 24px; padding: 44px 40px;\n");
      out.write("      width: 100%; max-width: 520px;\n");
      out.write("      position: relative; z-index: 1;\n");
      out.write("      box-shadow: 0 30px 80px rgba(0,0,0,0.5);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Header */\n");
      out.write("    .page-header { text-align: center; margin-bottom: 32px; }\n");
      out.write("    .header-icon {\n");
      out.write("      width: 64px; height: 64px;\n");
      out.write("      background: linear-gradient(135deg, var(--accent), #c0392b);\n");
      out.write("      border-radius: 18px;\n");
      out.write("      display: flex; align-items: center; justify-content: center;\n");
      out.write("      font-size: 1.6rem; margin: 0 auto 14px;\n");
      out.write("      box-shadow: 0 8px 24px rgba(232,148,58,0.3);\n");
      out.write("    }\n");
      out.write("    .page-header h2 {\n");
      out.write("      font-family: 'Playfair Display', serif;\n");
      out.write("      font-size: 1.6rem; font-weight: 700;\n");
      out.write("    }\n");
      out.write("    .page-header h2 span { color: var(--accent); }\n");
      out.write("    .page-header p { color: var(--muted); font-size: 0.82rem; margin-top: 6px; }\n");
      out.write("\n");
      out.write("    /* Alert banner */\n");
      out.write("    .review-alert {\n");
      out.write("      background: rgba(232,148,58,0.08);\n");
      out.write("      border: 1px solid rgba(232,148,58,0.2);\n");
      out.write("      border-radius: 12px; padding: 12px 16px;\n");
      out.write("      display: flex; align-items: center; gap: 10px;\n");
      out.write("      margin-bottom: 28px; font-size: 0.82rem; color: var(--accent);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* Section label */\n");
      out.write("    .section-label {\n");
      out.write("      font-size: 0.68rem; font-weight: 600; letter-spacing: 1px;\n");
      out.write("      text-transform: uppercase; color: var(--muted);\n");
      out.write("      margin: 22px 0 12px;\n");
      out.write("      display: flex; align-items: center; gap: 8px;\n");
      out.write("    }\n");
      out.write("    .section-label::after { content: ''; flex: 1; height: 1px; background: var(--border); }\n");
      out.write("    .section-label i { color: var(--accent); }\n");
      out.write("\n");
      out.write("    /* Detail rows */\n");
      out.write("    .detail-grid {\n");
      out.write("      display: flex; flex-direction: column; gap: 2px;\n");
      out.write("      background: var(--surface2);\n");
      out.write("      border: 1px solid var(--border);\n");
      out.write("      border-radius: 14px; overflow: hidden;\n");
      out.write("      margin-bottom: 4px;\n");
      out.write("    }\n");
      out.write("    .detail-row {\n");
      out.write("      display: flex; align-items: center;\n");
      out.write("      padding: 12px 16px; gap: 12px;\n");
      out.write("      border-bottom: 1px solid var(--border);\n");
      out.write("      transition: background 0.2s;\n");
      out.write("    }\n");
      out.write("    .detail-row:last-child { border-bottom: none; }\n");
      out.write("    .detail-row:hover { background: rgba(255,255,255,0.02); }\n");
      out.write("    .detail-icon {\n");
      out.write("      width: 32px; height: 32px; border-radius: 8px;\n");
      out.write("      background: rgba(232,148,58,0.1);\n");
      out.write("      display: flex; align-items: center; justify-content: center;\n");
      out.write("      flex-shrink: 0;\n");
      out.write("    }\n");
      out.write("    .detail-icon i { color: var(--accent); font-size: 0.78rem; }\n");
      out.write("    .detail-content { flex: 1; min-width: 0; }\n");
      out.write("    .detail-label {\n");
      out.write("      font-size: 0.68rem; color: var(--muted);\n");
      out.write("      text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 2px;\n");
      out.write("    }\n");
      out.write("    .detail-value {\n");
      out.write("      font-size: 0.9rem; font-weight: 500; color: var(--text);\n");
      out.write("      white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n");
      out.write("    }\n");
      out.write("    .detail-value.masked { letter-spacing: 3px; color: var(--muted); }\n");
      out.write("\n");
      out.write("    /* Action buttons */\n");
      out.write("    .actions { display: flex; gap: 12px; margin-top: 28px; }\n");
      out.write("    .btn-back {\n");
      out.write("      flex: 1; padding: 14px;\n");
      out.write("      background: transparent;\n");
      out.write("      border: 1.5px solid var(--border);\n");
      out.write("      border-radius: 12px; color: var(--muted);\n");
      out.write("      font-family: 'Poppins', sans-serif;\n");
      out.write("      font-size: 0.88rem; font-weight: 500;\n");
      out.write("      cursor: pointer; text-decoration: none;\n");
      out.write("      display: flex; align-items: center; justify-content: center; gap: 8px;\n");
      out.write("      transition: all 0.25s;\n");
      out.write("    }\n");
      out.write("    .btn-back:hover { border-color: var(--accent); color: var(--accent); }\n");
      out.write("    .btn-confirm {\n");
      out.write("      flex: 2; padding: 14px;\n");
      out.write("      background: linear-gradient(135deg, #2ed573, #1abc9c);\n");
      out.write("      color: #0d0d0d;\n");
      out.write("      font-family: 'Poppins', sans-serif;\n");
      out.write("      font-size: 0.95rem; font-weight: 700;\n");
      out.write("      border: none; border-radius: 12px;\n");
      out.write("      cursor: pointer; letter-spacing: 0.4px;\n");
      out.write("      transition: opacity 0.25s, transform 0.2s, box-shadow 0.25s;\n");
      out.write("      box-shadow: 0 6px 20px rgba(46,213,117,0.25);\n");
      out.write("      display: flex; align-items: center; justify-content: center; gap: 8px;\n");
      out.write("    }\n");
      out.write("    .btn-confirm:hover {\n");
      out.write("      opacity: 0.9; transform: translateY(-2px);\n");
      out.write("      box-shadow: 0 10px 28px rgba(46,213,117,0.4);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @media (max-width: 480px) {\n");
      out.write("      .card { padding: 32px 18px; }\n");
      out.write("      .actions { flex-direction: column; }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");

RegBean rb = (RegBean) application.getAttribute("beanRef");

      out.write("\n");
      out.write("  <div class=\"card\">\n");
      out.write("\n");
      out.write("    <div class=\"page-header\">\n");
      out.write("      <div class=\"header-icon\">📋</div>\n");
      out.write("      <h2>Review Your <span>Details</span></h2>\n");
      out.write("      <p>Please confirm everything looks correct before registering</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"review-alert\">\n");
      out.write("      <i class=\"fa fa-circle-info\"></i>\n");
      out.write("      Double-check your details below. Click <strong>&nbsp;Confirm & Register&nbsp;</strong> when ready.\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Personal Info -->\n");
      out.write("    <div class=\"section-label\"><i class=\"fa fa-user\"></i> Personal Information</div>\n");
      out.write("    <div class=\"detail-grid\">\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-user\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Username</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getuName() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-lock\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Password</div>\n");
      out.write("          <div class=\"detail-value masked\">••••••••</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-id-card\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Full Name</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getfName() );
      out.write(' ');
      out.print( rb.getlName() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Contact Info -->\n");
      out.write("    <div class=\"section-label\"><i class=\"fa fa-address-book\"></i> Contact Information</div>\n");
      out.write("    <div class=\"detail-grid\">\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-envelope\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Email</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getMid() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-phone\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Phone</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getMob() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-map-pin\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Location</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getLoc() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-location-dot\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Address</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getAddr() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Bank Info -->\n");
      out.write("    <div class=\"section-label\"><i class=\"fa fa-building-columns\"></i> Bank Details</div>\n");
      out.write("    <div class=\"detail-grid\">\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-credit-card\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">Account Number</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getAccno() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"detail-row\">\n");
      out.write("        <div class=\"detail-icon\"><i class=\"fa fa-hashtag\"></i></div>\n");
      out.write("        <div class=\"detail-content\">\n");
      out.write("          <div class=\"detail-label\">IFSC Code</div>\n");
      out.write("          <div class=\"detail-value\">");
      out.print( rb.getIfsc() );
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Actions -->\n");
      out.write("    <div class=\"actions\">\n");
      out.write("      <a href=\"input2.html\" class=\"btn-back\">\n");
      out.write("        <i class=\"fa fa-arrow-left\"></i> Edit\n");
      out.write("      </a>\n");
      out.write("      <form action=\"final\" method=\"post\" style=\"flex:2;display:flex;\">\n");
      out.write("        <button type=\"submit\" class=\"btn-confirm\" style=\"flex:1;\">\n");
      out.write("          <i class=\"fa fa-check-circle\"></i> Confirm & Register\n");
      out.write("        </button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
