/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2026-03-15 12:06:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ViewDish_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("  <title>Our Menu | Mommy's Kitchen</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Poppins:wght@300;400;500;600&display=swap\" rel=\"stylesheet\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"/>\n");
      out.write("  <style>\n");
      out.write("    *, *::before, *::after { margin:0; padding:0; box-sizing:border-box; }\n");
      out.write("    :root { --bg:#0d0d0d; --surface:#1a1a1a; --surface2:#222; --border:rgba(255,255,255,0.08); --accent:#e8943a; --text:#f0f0f0; --muted:#777; }\n");
      out.write("    body { font-family:'Poppins',sans-serif; background:var(--bg); color:var(--text); min-height:100vh; }\n");
      out.write("    body::before, body::after { content:''; position:fixed; border-radius:50%; filter:blur(100px); opacity:0.1; pointer-events:none; z-index:0; }\n");
      out.write("    body::before { width:600px; height:600px; background:var(--accent); top:-200px; left:-200px; }\n");
      out.write("    body::after  { width:500px; height:500px; background:#c0392b; bottom:-150px; right:-150px; }\n");
      out.write("    nav {\n");
      out.write("      position:fixed; top:0; width:100%; z-index:100;\n");
      out.write("      display:flex; justify-content:space-between; align-items:center;\n");
      out.write("      padding:16px 6%; background:rgba(13,13,13,0.88);\n");
      out.write("      backdrop-filter:blur(14px); border-bottom:1px solid var(--border);\n");
      out.write("    }\n");
      out.write("    .logo { font-family:'Playfair Display',serif; font-size:1.4rem; font-weight:700; color:var(--accent); text-decoration:none; }\n");
      out.write("    .logo span { color:var(--text); }\n");
      out.write("    .nav-right { display:flex; align-items:center; gap:16px; }\n");
      out.write("    .nav-badge { background:rgba(232,148,58,0.12); color:var(--accent); border:1px solid rgba(232,148,58,0.25); border-radius:20px; padding:4px 12px; font-size:0.72rem; font-weight:600; }\n");
      out.write("    .nav-back { color:var(--muted); text-decoration:none; font-size:0.82rem; display:flex; align-items:center; gap:6px; transition:color 0.2s; }\n");
      out.write("    .nav-back:hover { color:var(--accent); }\n");
      out.write("    .main { padding:100px 6% 60px; position:relative; z-index:1; }\n");
      out.write("    .page-header { margin-bottom:36px; }\n");
      out.write("    .page-header h1 { font-family:'Playfair Display',serif; font-size:2.2rem; margin-bottom:8px; }\n");
      out.write("    .page-header h1 span { color:var(--accent); }\n");
      out.write("    .page-header p { color:var(--muted); font-size:0.88rem; }\n");
      out.write("    /* Empty state */\n");
      out.write("    .empty-state { text-align:center; padding:80px 20px; }\n");
      out.write("    .empty-icon { font-size:4rem; margin-bottom:16px; }\n");
      out.write("    .empty-state h3 { font-family:'Playfair Display',serif; font-size:1.4rem; margin-bottom:8px; color:var(--muted); }\n");
      out.write("    /* Menu grid */\n");
      out.write("    .menu-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:24px; }\n");
      out.write("    .dish-card { background:var(--surface); border:1px solid var(--border); border-radius:20px; overflow:hidden; transition:transform 0.3s,box-shadow 0.3s; }\n");
      out.write("    .dish-card:hover { transform:translateY(-6px); box-shadow:0 20px 50px rgba(0,0,0,0.4); }\n");
      out.write("    .dish-img { height:160px; background:linear-gradient(135deg,rgba(232,148,58,0.15),rgba(192,57,43,0.1)); display:flex; align-items:center; justify-content:center; font-size:3.5rem; border-bottom:1px solid var(--border); }\n");
      out.write("    .dish-body { padding:20px; }\n");
      out.write("    .dish-name { font-size:1.05rem; font-weight:600; margin-bottom:6px; }\n");
      out.write("    .dish-price { font-size:1.2rem; font-weight:700; color:var(--accent); margin-bottom:12px; }\n");
      out.write("    .dish-meta { display:flex; flex-wrap:wrap; gap:8px; margin-bottom:14px; }\n");
      out.write("    .meta-tag { display:inline-flex; align-items:center; gap:5px; padding:3px 10px; border-radius:20px; font-size:0.7rem; font-weight:500; }\n");
      out.write("    .tag-time  { background:rgba(52,152,219,0.1);  color:#3498db; }\n");
      out.write("    .tag-avail { background:rgba(46,213,115,0.1);  color:#2ed573; }\n");
      out.write("    .tag-stock { background:rgba(232,148,58,0.1);  color:var(--accent); }\n");
      out.write("    .tag-no    { background:rgba(231,76,60,0.1);   color:#e74c3c; }\n");
      out.write("    .btn-order { width:100%; padding:11px; background:linear-gradient(135deg,var(--accent),#d4782a); color:#0d0d0d; font-family:'Poppins',sans-serif; font-size:0.85rem; font-weight:700; border:none; border-radius:10px; cursor:pointer; transition:opacity 0.25s,transform 0.2s; display:flex; align-items:center; justify-content:center; gap:6px; }\n");
      out.write("    .btn-order:hover { opacity:0.9; transform:translateY(-1px); }\n");
      out.write("    @media(max-width:600px) { .menu-grid{grid-template-columns:1fr;} }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");

List<String[]> dishes = (List<String[]>) request.getAttribute("dishes");

      out.write("\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"clogin_success.jsp\" class=\"logo\">Mommy's<span> Kitchen</span></a>\n");
      out.write("    <div class=\"nav-right\">\n");
      out.write("      <span class=\"nav-badge\"><i class=\"fa fa-bowl-food\"></i> &nbsp;MENU</span>\n");
      out.write("      <a href=\"clogin_success.jsp\" class=\"nav-back\"><i class=\"fa fa-arrow-left\"></i> Dashboard</a>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <div class=\"main\">\n");
      out.write("    <div class=\"page-header\">\n");
      out.write("      <h1>Our <span>Menu</span></h1>\n");
      out.write("      <p>Fresh dishes prepared with love — order your favourite!</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 if (dishes == null || dishes.isEmpty()) { 
      out.write("\n");
      out.write("    <div class=\"empty-state\">\n");
      out.write("      <div class=\"empty-icon\">🍽️</div>\n");
      out.write("      <h3>No dishes available yet</h3>\n");
      out.write("      <p style=\"color:var(--muted);font-size:0.85rem;margin-top:8px;\">Check back soon — the chef is cooking!</p>\n");
      out.write("    </div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <div class=\"menu-grid\">\n");
      out.write("      ");
 for (String[] d : dishes) {
           String dname  = d[0] != null ? d[0] : "";
           String dprice = d[1] != null ? d[1] : "";
           String tpa    = d[2] != null ? d[2] : "";
           String deliv  = d[3] != null ? d[3] : "";
           String phno   = d[4] != null ? d[4] : "";
           String avail  = d[5] != null ? d[5] : "";
           String emoji  = dname.toLowerCase().contains("chicken") ? "🍗" :
                           dname.toLowerCase().contains("rice")    ? "🍚" :
                           dname.toLowerCase().contains("pizza")   ? "🍕" :
                           dname.toLowerCase().contains("burger")  ? "🍔" :
                           dname.toLowerCase().contains("dal")     ? "🍲" :
                           dname.toLowerCase().contains("paneer")  ? "🧀" : "🍛";
      
      out.write("\n");
      out.write("      <div class=\"dish-card\">\n");
      out.write("        <div class=\"dish-img\">");
      out.print( emoji );
      out.write("</div>\n");
      out.write("        <div class=\"dish-body\">\n");
      out.write("          <div class=\"dish-name\">");
      out.print( dname );
      out.write("</div>\n");
      out.write("          <div class=\"dish-price\">₹");
      out.print( dprice );
      out.write("</div>\n");
      out.write("          <div class=\"dish-meta\">\n");
      out.write("            <span class=\"meta-tag tag-time\"><i class=\"fa fa-clock\"></i> ");
      out.print( tpa );
      out.write("</span>\n");
      out.write("            <span class=\"meta-tag ");
      out.print( avail.equalsIgnoreCase("yes") ? "tag-avail" : "tag-no" );
      out.write("\">\n");
      out.write("              <i class=\"fa fa-circle\"></i> ");
      out.print( avail.equalsIgnoreCase("yes") ? "In Stock" : "Out of Stock" );
      out.write("\n");
      out.write("            </span>\n");
      out.write("            <span class=\"meta-tag ");
      out.print( deliv.equalsIgnoreCase("yes") ? "tag-stock" : "tag-no" );
      out.write("\">\n");
      out.write("              <i class=\"fa fa-truck\"></i> ");
      out.print( deliv.equalsIgnoreCase("yes") ? "Delivery" : "No Delivery" );
      out.write("\n");
      out.write("            </span>\n");
      out.write("          </div>\n");
      out.write("          <form action=\"placeorder\" method=\"post\" style=\"margin:0\"><input type=\"hidden\" name=\"dname\" value=\"");
      out.print( dname );
      out.write("\"/><input type=\"hidden\" name=\"dprice\" value=\"");
      out.print( dprice );
      out.write("\"/><input type=\"hidden\" name=\"cuname\" value=\"customer\"/><button type=\"submit\" class=\"btn-order\"><i class=\"fa fa-cart-plus\"></i> Order Now</button></form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
